# Generated by Django 3.2 on 2021-06-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210531_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
