# Generated by Django 3.1.13 on 2021-12-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211214_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
